name: Push commits notifications Telegram chat

on:
  push:
    branches:
      - master
    
jobs:
  push_noti:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            Branch: ${{ commit.ref }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}